version: '3.6'

services:
  duplicity:
    container_name: ${COMPOSE_PROJECT_NAME}-backup
    build:
        context: ./latest
    image: clarity/duplicity
    environment:
        - TMPDIR=/tmp
        - PASSPHRASE=${PASSPHRASE}
    volumes:
        - type: tmpfs
          target: /tmp
        - type: volume
          source: gnupg
          target: /home/duplicity/.gnupg
        - type: volume
          source: cache
          target: /home/duplicity/.cache/duplicity
        - type: bind
          source: ./filelist.txt
          target: /home/duplicity/filelist.txt
        - type: bind
          source: ./backup
          target: /backup
        - type: bind
          source: /docker
          target: /data/docker
        - type: bind
          source: /var/lib/docker/volumes
          target: /data/docker-volumes
    command: -v4 --include-filelist=/home/duplicity/filelist.txt --full-if-older-than=2M --allow-source-mismatch /data file:///backup 
volumes:
  gnupg:
    name: ${COMPOSE_PROJECT_NAME}_gnupg
  cache:    
    name: ${COMPOSE_PROJECT_NAME}_cache  
networks:
  default:
    external:
      name: ${NETWORK:-clarity}
      