version: '3.6'

services:
  duplicity:
    container_name: ${COMPOSE_PROJECT_NAME}-restore
    image: clarity/duplicity
    environment:
        - TMPDIR=/tmp
        - PASSPHRASE=${PASSPHRASE}
    volumes:
        - type: tmpfs
          target: /tmp
        - type: bind
          source: ./duplicity_gnupg
          target: /home/duplicity/.gnupg
        - type: bind
          source: ./duplicity_cache
          target: /home/duplicity/.cache/duplicity
        - type: bind
          source: ./filelist.txt
          target: /home/duplicity/filelist.txt
        - type: bind
          source: ./backup
          target: /backup
        - type: bind
          source: ./restore
          target: /data
    command: duplicity --force --allow-source-mismatch restore file:///backup /data

networks:
  default:
    external:
      name: ${NETWORK:-clarity}