version: '3.6'

services:
  duplicity:
    container_name: ${COMPOSE_PROJECT_NAME}-restore
    image: clarity/duplicity
    environment:
        - TMPDIR=/tmp
        - PASSPHRASE=${PASSPHRASE}
    volumes:
        - type: tmpfs
          target: /tmp
        - type: volume
          source: gnupg
          target: /home/duplicity/.gnupg
        - type: volume
          source: cache
          target: /home/duplicity/.cache/duplicity
        - type: bind
          source: ./filelist.txt
          target: /home/duplicity/filelist.txt
        - type: bind
          source: ./backup
          target: /backup
        - type: bind
          source: ./restore
          target: /data
    command: -v6 --force --allow-source-mismatch restore file:///backup /data
volumes:
  gnupg:
    name: ${COMPOSE_PROJECT_NAME}_gnupg
  cache:    
    name: ${COMPOSE_PROJECT_NAME}_cache  
networks:
  default:
    external:
      name: ${NETWORK:-clarity}